// import alias "@/" (that was defined at the time of porject creation) used to import Header. Absolute path is not needed while using import alias. It's cnfoguration is written in tsconfig.json file/paths.

import Header from '@/components/layout/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}</body>
    </html>
  )
}
